import { test, expect } from '@playwright/test';

/**
 * **Fluxo 1 da §25 — Visitante.** Home carrega, hero abre matéria, briefing
 * abre, categoria filtra.
 *
 * As asserções são **estruturais**, não sobre texto: papel, URL, landmark. O
 * site é bilíngue e o conteúdo muda todo dia — um smoke que casa manchete
 * reprova quando o pipeline roda, e reprovar por conteúdo novo é ruído que
 * ensina a ignorar o gate.
 *
 * O que este arquivo de fato prova, e nenhum teste de unidade prova: que **os
 * dois deploys chegaram**. A Home chama `GET /api/home` no servidor; se o build
 * do web tiver corrido antes de a API subir, é aqui que aparece — foi assim que
 * a `/news` foi ao ar com as oito categorias zeradas.
 */

test.describe('visitante', () => {
  test('a Home carrega com conteúdo do dia, não com o estado vazio', async ({
    page,
  }) => {
    await page.goto('/pt-BR');

    await expect(page.locator('main#conteudo')).toBeVisible();

    // O destaque do dia é o bloco que só existe quando a API respondeu. A Home
    // desenha sem ele — é estado normal —, e é justamente por isso que a
    // ausência dele em produção significa que o dado não chegou.
    await expect(page.getByRole('article', { name: /destaque|top story/i })).toBeVisible();

    // Manchetes de verdade, não esqueleto.
    const storyLinks = page.locator('a[href*="/news/"]');
    expect(await storyLinks.count()).toBeGreaterThan(5);
  });

  test('o hero abre a matéria', async ({ page }) => {
    await page.goto('/pt-BR');

    const hero = page
      .getByRole('article', { name: /destaque|top story/i })
      .locator('a[href*="/news/"]')
      .first();
    await hero.click();

    await expect(page).toHaveURL(/\/pt-BR\/news\/[0-9a-f-]{36}$/);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    // A tela de leitura **é** um artigo, e isso foi decidido na auditoria de
    // leitor de tela da Fase 7 — era uma pilha de `div` com um `h1` no meio.
    await expect(page.locator('main article').first()).toBeVisible();
  });

  test('o briefing do dia abre e declara que foi gerado por IA', async ({ page }) => {
    await page.goto('/pt-BR');

    const briefing = page.locator('a[href*="/article/"]').first();
    await briefing.click();

    await expect(page).toHaveURL(/\/pt-BR\/article\/\d{4}-\d{2}-\d{2}$/);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();

    // A transparência de IA é da §8 e só existe nesta tela — carimbar a
    // notícia de uma redação como produzida por IA mentiria na direção que
    // mais custa aqui. Se ela sumir, o produto quebrou uma promessa editorial.
    await expect(page.getByText(/intelig[êe]ncia artificial|generated by ai/i).first()).toBeVisible();
  });

  test('a faixa de assuntos leva ao recorte do acervo', async ({ page }) => {
    await page.goto('/pt-BR');

    await page.locator('a[href*="/news?category="]').first().click();

    /**
     * A asserção é sobre **qual recorte**, e não sobre *aquela* categoria.
     *
     * A primeira versão lia o `href` e depois clicava, esperando o mesmo valor
     * — e reprovou com "esperava POLITICS, recebeu TECHNOLOGY". O locator
     * reconsulta o DOM a cada ação, e entre a leitura e o clique a hidratação
     * trocou o primeiro elemento. Guardar o valor de antes seria testar a
     * ordem da faixa, que muda com o acervo; o que o produto promete é que o
     * clique leva ao acervo filtrado por uma das oito.
     */
    await expect(page).toHaveURL(
      /\/pt-BR\/news\?category=(TECHNOLOGY|POLITICS|ECONOMY|SPORTS|SCIENCE|ENTERTAINMENT|WORLD|HEALTH)/,
    );
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  });
});
